server:
  port: 8445

spring:
  application:
    name: feign

  cloud:
    nacos:
      discovery:
        server-addr: http://10.60.80.115:8848

feign:
  circuitbreaker:
    enabled: true
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: FULL

logging:
  level:
    com.zsy.feign: debug